#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Reporting service package entry point."""

from .engine.report_engine import (
    ReportGenerator,
    EXIFReportGenerator,
    create_report_generator,
)
from .infrastructure import (
    AssetManager,
    HTMLTemplateService,
    HTMLStyleService,
    HTMLContentService,
    TemplateRenderer,
    ReportData,
    ReportConfig,
    ReportSection,
    SectionType,
    TableData,
    ChartData,
    ChartType,
    KPIData,
    create_table_section,
    create_chart_section,
    create_kpi_section,
    create_text_section,
    create_html_section,
)
from .manager import UnifiedReportManager, ReportHistoryItem
from .domains import (
    ExifComparisonReportGenerator,
    generate_trend_charts_html,
    generate_chart_scripts,
    generate_comparison_table,
    generate_statistics_table,
    generate_topn_anomaly_table,
    generate_kpi_cards,
    generate_per_image_rpg_bpg_analysis,
    legacy_generate_statistics_table,
    legacy_generate_kpi_cards,
    legacy_generate_comparison_table,
    legacy_generate_per_image_rpg_bpg_analysis,
    generate_sgw_baseline_analysis,
    legacy_generate_topn_anomaly_table,
    MapMultiDimensionalReportGenerator,
)

__all__ = [
    'ReportGenerator',
    'EXIFReportGenerator',
    'create_report_generator',
    'AssetManager',
    'HTMLTemplateService',
    'HTMLStyleService',
    'HTMLContentService',
    'TemplateRenderer',
    'ReportData',
    'ReportConfig',
    'ReportSection',
    'SectionType',
    'TableData',
    'ChartData',
    'ChartType',
    'KPIData',
    'create_table_section',
    'create_chart_section',
    'create_kpi_section',
    'create_text_section',
    'create_html_section',
    'UnifiedReportManager',
    'ReportHistoryItem',
    'ExifComparisonReportGenerator',
    'generate_trend_charts_html',
    'generate_chart_scripts',
    'generate_comparison_table',
    'generate_statistics_table',
    'generate_topn_anomaly_table',
    'generate_kpi_cards',
    'generate_per_image_rpg_bpg_analysis',
    'legacy_generate_statistics_table',
    'legacy_generate_kpi_cards',
    'legacy_generate_comparison_table',
    'legacy_generate_per_image_rpg_bpg_analysis',
    'generate_sgw_baseline_analysis',
    'legacy_generate_topn_anomaly_table',
    'MapMultiDimensionalReportGenerator',
]
